'use client'
import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/index.module.css";
import SideBar from "@/components/side_bar"
import { Typography, Box, Grid, Button } from "@mui/material";
import Add_Button from "@/components/addButton"
import Modal from "@/components/modals/modal"
import { useEffect, useState } from "react";
import MenuIcon from '@mui/icons-material/Menu';
import {useMediaQuery  } from "@mui/material"
import Table from '../components/tables/customer';
const inter = Inter({ subsets: ["latin"] });
import { useDispatch } from "react-redux";
import { getAllCustomer } from '../store/slices/CustomerAPI'

export default function Home() {
  const dispatch = useDispatch()
  const [modalOpen, setModalOpen] = useState(false)
  const [sideOpen, setSideValue] = useState(false)
  const [isEditForm, setIsEditForm] = useState(false)
  const tablet = useMediaQuery('(max-width:1000px)');


  useEffect(() => {
    dispatch(getAllCustomer());
  }, []);
  



  const openModal = () => {
    setModalOpen(true)
    setIsEditForm(false)
  }



  const handleSideMenu = ()=>{
    setSideValue(true)
  }


  // handle edit button in table
  const handleEditButton = ()=>{
    setModalOpen(true)
    setIsEditForm(true)
}




  // tables Data

  const tableHeaders = [
    {value : "", sortable: false}, 
    {value : "username",sortable: true},
    {value : "CustomerName", sortable : true},
    {value : "Email", sortable : true},
    {value : "", sortable : false}
  ]


  return (
    <>
      <Head>
        <title>SAVIYNT</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link rel="icon" href="/favicon.ico"/> */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet"></link>
      </Head>
      <main>
        {/* sidebar */}
        <Box className={styles.mainOuterBox}>
          <Box>
            <SideBar sideOpen={sideOpen} setSideValue={setSideValue}/>
          </Box>

          <Box className={styles.contentBox}>
            {/* header */}
            <Box className={styles.pageHeader}>
              <h1 style={{ margin: "0px" }}>CUSTOMERS</h1>
              {tablet ? 
               <Button sx={{
                marginLeft : "auto"
               }} onClick={handleSideMenu}>
                  <MenuIcon className={styles.textColor}/>
               </Button>
               : ""
              }
            </Box>
            {/* header end  */}
            {/* Body */}
            <Box className={styles.mainContent}>
              <Add_Button text="Add New Customer" type="add" action={openModal} />

              {/* customer tables */}
              <Box className={styles.table_responsive} sx={{marginTop : "50px"}}>
                
                <Table data={[]} isLoading={false} tableHeader={tableHeaders} handleEditButton={handleEditButton}/>
                
              </Box>
            </Box>
          </Box>
        </Box>

            {/* edit and update form modal */}
        <Modal  open={modalOpen} setModalOpen={setModalOpen} isEditForm={isEditForm}/>
      </main>
    </>
  );
}
